In [6]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Embedding, SimpleRNN, Dense

In [7]:
sentences = [
 "I love this product",
 "This movie made me smile",
 "Service was friendly and quick",
 "Today felt bright and happy",
 "This is the best day",
 "Absolutely fantastic experience",
 "I enjoyed every single moment",
 "Great job, well done",
 "The food tasted delicious",
 "Totally recommend to everyone",
 "Very satisfied with results",
 "This worked better than expected",
 "Amazing quality and value",
 "Such a pleasant surprise",
 "I feel positive about this",
 "I hate this product",
 "This movie bored me",
 "Service was rude and slow",
 "Today was cold and lonely",
 "This is the worst day",
 "Terrible experience overall",
 "I regret buying this",
 "Very disappointed with results",
 "The food tasted awful",
 "Do not recommend this",
 "It broke after one use",
 "Not worth the money",
 "Utterly frustrating and annoying",
 "I feel negative about this",
 "Such a waste of time",
]
labels = [1]*15 + [0]*15
labels = np.array(labels)

In [8]:
vocab_size = 2000
tokenizer = Tokenizer(num_words= vocab_size, oov_token= "<OOV>")
tokenizer.fit_on_texts(sentences)
sequence = tokenizer.texts_to_sequences(sentences)
maxlen = max(len(s) for s in sequence)
X = pad_sequences(sequence,maxlen = maxlen,padding= 'post')
y = labels

In [9]:
X[29]

array([21, 22, 85, 86, 87], dtype=int32)

In [10]:
embed_dim = 16
rnn_units = 8

inp = Input(
    shape=(maxlen,),
    dtype="int32",
    name="input"
)

x = Embedding(
    input_dim=vocab_size,
    output_dim=embed_dim,
    mask_zero=True,
    name="Embed"
)(inp)

RNN = SimpleRNN(
    units=rnn_units,
    return_sequences=True,
    return_state=True,
    name="Simple_RNN"
)

x_seq, x_last = RNN(x)

out = Dense(
    1,
    activation="sigmoid",
    name="out"
)(x_last)

model = Model(
    inputs=inp,
    outputs=out
)

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input (InputLayer)  │ (None, 5)         │          0 │ -                 │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Embed (Embedding)   │ (None, 5, 16)     │     32,000 │ input[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ not_equal_1         │ (None, 5)         │          0 │ input[0][0]       │
│ (NotEqual)          │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Simple_RNN          │ [(None, 5, 8),    │        200 │ Embed[0][0],      │
│ (SimpleRNN)         │ (None, 8)]        │            │ not_equal_1[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ out (Dense)         │ (None, 1)         │          9 │ Simple_RNN[0][1]  │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 32,209 (125.82 KB)

 Trainable params: 32,209 (125.82 KB)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.fit(X,y,epochs = 50, batch_size= 8, verbose= 1)

Epoch 1/50


2026-09-03 06:24:03.611781: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


4/4 ━━━━━━━━━━━━━━━━━━━━ 4s 418ms/step - accuracy: 0.4333 - loss: 0.6931
Epoch 2/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.6000 - loss: 0.6822
Epoch 3/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.8333 - loss: 0.6730
Epoch 4/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.9000 - loss: 0.6643
Epoch 5/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.9000 - loss: 0.6552
Epoch 6/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.9000 - loss: 0.6457
Epoch 7/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.9000 - loss: 0.6351
Epoch 8/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.9000 - loss: 0.6237
Epoch 9/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.9333 - loss: 0.6108
Epoch 10/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.9667 - loss: 0.5969
Epoch 11/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.9667 - loss: 0.5820
Epoch 12/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.9667 - loss: 0.5666
Epoch 13/50

In [13]:
from tensorflow.keras.layers import Input
from tensorflow.keras.layers import SimpleRNN as SRNN
from tensorflow.keras.models import Model
import numpy as np

seq_inp = Input(
    shape=(maxlen,),
    dtype='int32'
)

# Reuse trained embedding
seq_emb = model.get_layer('Embed')(seq_inp)

# Create RNN with return_sequences=True
rnn_seq = SRNN(
    units=rnn_units,
    return_sequences=True,
    name='rnn_seq'
)

seq_hidden = rnn_seq(seq_emb)

# Copy trained RNN weights
trained_weights = model.get_layer('Simple_RNN').get_weights()
rnn_seq.set_weights(trained_weights)

print("Copied RNN weights into sequence-inspection RNN.")

# Inspection model
inspect_model = Model(
    inputs=seq_inp,
    outputs=seq_hidden
)

# Inspect first example
idx = 0
example_seq = X[idx:idx+1]

hidden_seq = inspect_model.predict(example_seq)

print("Sentence:", sentences[idx])
print("Token ids:", example_seq)
print("Hidden states per timestep shape:", hidden_seq.shape)

print("Hidden states (timesteps × units):")
print(np.round(hidden_seq[0], 3))

Copied RNN weights into sequence-inspection RNN.
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 981ms/step
Sentence: I love this product
Token ids: [[ 3 26  2  7  0]]
Hidden states per timestep shape: (1, 5, 8)
Hidden states (timesteps × units):
[[ 0.005 -0.019 -0.045 -0.066  0.069  0.008 -0.052 -0.062]
 [-0.081  0.339 -0.359  0.21   0.156  0.278 -0.175 -0.254]
 [-0.096 -0.501  0.539 -0.634  0.092  0.325 -0.512  0.011]
 [ 0.488  0.381 -0.735  0.502 -0.73  -0.264  0.757  0.736]
 [ 0.488  0.381 -0.735  0.502 -0.73  -0.264  0.757  0.736]]
