In [2]:
import tensorflow as tf

In [3]:
print("TensorFlow:", tf.__version__)

tf.config.list_physical_devices("GPU")

TensorFlow: 2.18.1


[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [4]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 5524177947108220359
xla_global_id: -1
, name: "/device:GPU:0"
device_type: "GPU"
locality {
  bus_id: 1
}
incarnation: 16371518414033593426
physical_device_desc: "device: 0, name: METAL, pci bus id: <undefined>"
xla_global_id: -1
]


2026-08-23 23:26:04.274331: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1
2026-08-23 23:26:04.274365: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2026-08-23 23:26:04.274372: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
I0000 00:00:1787507764.274957 10128801 pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
I0000 00:00:1787507764.275055 10128801 pluggable_device_factory.cc:271] Created TensorFlow device (/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [5]:
s = tf.constant(1) # Scaler
a = tf.constant([1,2,3,4]) # 1D Array
b = tf.constant([[1,2,3],[4,5,6]]) # 2D Array
z = tf.constant([[[1,2,3],[4,5,6]],[[9,8,7],[6,5,4]]]) # 3D Array

I0000 00:00:1787507764.289099 10128801 pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
I0000 00:00:1787507764.289117 10128801 pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [6]:
a

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [7]:
tf.shape(a)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([4], dtype=int32)>

In [8]:
a.shape

TensorShape([4])

In [9]:
z[1, 0, 1]

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [10]:
z[0,1,2]

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [11]:
b = tf.Variable([1,2,3,4,5,6], dtype= 'float64')

In [12]:
b.numpy

<bound method BaseResourceVariable.numpy of <tf.Variable 'Variable:0' shape=(6,) dtype=float64, numpy=array([1., 2., 3., 4., 5., 6.])>>

In [13]:
b.assign([10,20,30,40,50,60])

<tf.Variable 'UnreadVariable' shape=(6,) dtype=float64, numpy=array([10., 20., 30., 40., 50., 60.])>

In [14]:
b

<tf.Variable 'Variable:0' shape=(6,) dtype=float64, numpy=array([10., 20., 30., 40., 50., 60.])>

In [15]:
tf.ones((10,3))

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [16]:
tf.zeros((4,2))

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [17]:
tf.range(1,10,2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

In [18]:
tf.linspace(1,2,5)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1.  , 1.25, 1.5 , 1.75, 2.  ])>

In [19]:
tf.eye(4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [20]:
tf.random.set_seed(5)
a = tf.random.uniform((2,3),100,200,dtype = tf.int32)
tf.random.set_seed(7)
b = tf.random.uniform((2,3),100,200,dtype = tf.int32)

In [21]:
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[170, 171, 168],
       [166, 147, 196]], dtype=int32)>

In [22]:
b

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[154, 145, 107],
       [198, 184, 147]], dtype=int32)>

In [23]:
tf.random.normal((5,5),0,1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-2.2733312 , -1.6592106 , -0.26335675, -0.80923414,  1.0294315 ],
       [ 0.01906121,  0.96426606,  1.1359314 ,  0.07940757,  0.93018913],
       [ 0.19166751,  0.77001554,  0.02223603, -1.6922446 , -0.53064364],
       [-0.18471909,  1.0228829 ,  0.03157249, -1.3429264 , -0.70356727],
       [ 0.15260115,  1.128007  , -0.87830293, -1.2235895 ,  0.68281895]],
      dtype=float32)>

In [24]:
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[170, 171, 168],
       [166, 147, 196]], dtype=int32)>

In [25]:
tf.reshape(a,(-1,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[170, 171],
       [168, 166],
       [147, 196]], dtype=int32)>

In [26]:
tf.reshape(a,(-1))

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([170, 171, 168, 166, 147, 196], dtype=int32)>

In [ ]:
a = tf.constant([1,2,3,4,5])
b = tf.constant([10,20,30,40,50])

In [28]:
a+5

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 6,  7,  8,  9, 10], dtype=int32)>

In [29]:
a

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [30]:
a%5

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 0], dtype=int32)>

In [33]:
tf.logical_and(a==5,b==50)

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([False, False, False, False,  True])>

In [34]:
tf.reduce_max(a,axis=0)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [39]:
a = tf.constant([1,2,3,4,5])
b = tf.constant([10,20,30,40,50])