In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [2]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [3]:
df.head()

,soil_moisture,temperature_c,sunlight_hours,needs_water
0,0.10,34,9,1
1,0.15,30,8,1
2,0.20,26,7,1
3,0.25,22,4,0
4,0.40,28,8,0


In [4]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='str')

In [5]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

In [6]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X = scaler.fit_transform(X)

print(X)

[[0.06666667 0.9375     0.72727273]
 [0.13333333 0.6875     0.63636364]
 [0.2        0.4375     0.54545455]
 [0.26666667 0.1875     0.27272727]
 [0.46666667 0.5625     0.63636364]
 [0.73333333 0.6875     0.81818182]
 [0.4        0.         0.18181818]
 [0.17333333 0.1875     0.81818182]
 [0.53333333 1.         1.        ]
 [0.         0.3125     0.36363636]
 [1.         0.875      0.72727273]
 [0.29333333 0.875      0.90909091]
 [0.66666667 0.125      0.09090909]
 [0.86666667 0.375      0.45454545]
 [0.09333333 0.0625     0.        ]
 [0.33333333 0.625      0.72727273]]


In [7]:
X

array([[0.06666667, 0.9375    , 0.72727273],
       [0.13333333, 0.6875    , 0.63636364],
       [0.2       , 0.4375    , 0.54545455],
       [0.26666667, 0.1875    , 0.27272727],
       [0.46666667, 0.5625    , 0.63636364],
       [0.73333333, 0.6875    , 0.81818182],
       [0.4       , 0.        , 0.18181818],
       [0.17333333, 0.1875    , 0.81818182],
       [0.53333333, 1.        , 1.        ],
       [0.        , 0.3125    , 0.36363636],
       [1.        , 0.875     , 0.72727273],
       [0.29333333, 0.875     , 0.90909091],
       [0.66666667, 0.125     , 0.09090909],
       [0.86666667, 0.375     , 0.45454545],
       [0.09333333, 0.0625    , 0.        ],
       [0.33333333, 0.625     , 0.72727273]])

In [8]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.25, random_state=42, stratify=y)

In [9]:
model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)), # Input
    layers.Dense(8, activation= 'relu'),
    layers.Dense(1, activation= 'sigmoid'),
    
])

2026-09-02 00:59:22.353148: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1
2026-09-02 00:59:22.353340: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2026-09-02 00:59:22.353348: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
I0000 00:00:1788290962.353588 2210626 pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
I0000 00:00:1788290962.353812 2210626 pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [26]:
model.compile(optimizer=opt,loss='binary_crossentropy', metrics=['accuracy'])

In [27]:
history = model.fit(
    X_train,
    y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    batch_size=len(X_train),
    verbose= 1
)

history_minibatch = model.fit(
    X_train,
    y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    batch_size=100,
    verbose= 1
)


Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 454ms/step - accuracy: 0.9167 - loss: 0.4652 - val_accuracy: 1.0000 - val_loss: 0.4638
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.9167 - loss: 0.4633 - val_accuracy: 1.0000 - val_loss: 0.4612
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.9167 - loss: 0.4613 - val_accuracy: 1.0000 - val_loss: 0.4586
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.9167 - loss: 0.4594 - val_accuracy: 1.0000 - val_loss: 0.4561
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.9167 - loss: 0.4575 - val_accuracy: 1.0000 - val_loss: 0.4536
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.9167 - loss: 0.4556 - val_accuracy: 1.0000 - val_loss: 0.4511
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.9167 - loss: 0.4537 - val_accuracy: 1.0000 - val_loss: 0.4486
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.9167 - loss: 0.4518 - val_accuracy: 1.0000 - val_loss

In [22]:
from tensorflow.keras import optimizers

In [23]:
opt = optimizers.SGD(learning_rate = 0.01, momentum = 0.9)